DROP TABLE IF EXISTS DocumentLending;
DROP TABLE IF EXISTs Member;
DROP TABLE IF EXISTS Document;
DROP TABLE IF EXISTS AppUser;

CREATE TABLE AppUser (
	id SERIAL PRIMARY KEY,
	username VARCHAR(32) NOT NULL UNIQUE CHECK(LENGTH(TRIM(username)) > 0),
	password VARCHAR(32) NOT NULL CHECK(LENGTH(TRIM(password)) > 0)
);

CREATE TABLE Document (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL CHECK(LENGTH(TRIM(name)) > 0),
	author VARCHAR(255),
	description BPCHAR,
	uploader_id INTEGER REFERENCES AppUser NOT NULL
);

CREATE TABLE Member (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL CHECK(LENGTH(TRIM(name)) > 0)
);

CREATE TABLE DocumentLending (
	id SERIAL PRIMARY KEY,
	lend_time TIMESTAMP NOT NULL,
	member_id INTEGER REFERENCES Member NOT NULL,
	document_id INTEGER REFERENCES Document NOT NULL
);